import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/61AHiYyu3ZL._SX679_.jpg",
    title: "Smart Watch with Bluetooth Calling",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Rolex",
    color: "white",
    category: "watch",
  },
  {
    img: "https://rukminim2.flixcart.com/image/150/150/xif0q/tablet/8/p/n/vhu4401in-xiaomi-original-imagtz5x4tdswgyj.jpeg?q=70",
    title: "Xiaomi Pad 6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Xiaomi",
    color: "red",
    category: "iPad",
  },

  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/tablet/o/k/w/-original-imagj72ttsqcrehk.jpeg?q=70",
    title: "Apple iPad (10th Gen)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "green",
    category: "iPad",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/ktop5e80/tablet/q/y/c/mk8h3hn-a-apple-original-imag6yg2rfg6jbvn.jpeg?q=70",
    title: "Apple iPad mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "black",
    category: "iPad",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/ktop5e80/tablet/k/f/r/mlwr3hn-a-apple-original-imag6ygfbepytqcu.jpeg?q=70",
    title: "Apple iPad mini (6th Gen)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "green",
    category: "iPad",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/jwzabgw0/watch/c/h/g/ls2821-limestone-original-imafhjcr3xkxgqaz.jpeg?q=70",
    title: "Bleed Blue Day",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Bleed Blue",
    color: "black",
    category: "watch",
  },

  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/i/a/h/1-day-date-display-black-dial-ht-gr007-hamt-watches-men-original-imagwfcthrv2ztnx.jpeg?q=70",
    title: "Analog Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Rolex",
    color: "white",
    category: "watch",
  },

  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/tablet/r/4/m/-original-imagj72vqsfqgzpf.jpeg?q=70",
    title: "Apple iPad",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Apple",
    color: "green",
    category: "iPad",
  },

  {
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/h/i/x/-original-imagyr3vfpqrpkbv.jpeg?q=70",
    title: "Nothing Phone (2a) 5G",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "Phone",
  },

  {
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/v/b/-original-imagt4td4q9u7kxx.jpeg?q=70",
    title: "POCO C51 Phone",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Poco",
    color: "green",
    category: "Phone",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/m/f/g34-5g-pb1v0002in-motorola-original-imagwu4rayqhgfjh.jpeg?q=70",
    title: "Motorola G34 5G Phone",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Motorola",
    color: "red",
    category: "Phone",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/c/k/9/g34-5g-pb1v0001in-motorola-original-imagwu4r4xze9jwz.jpeg?q=70",
    title: "Motorola G34 5G (Ice Blue, 128 GB)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Motorola",
    color: "black",
    category: "Phone",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kpbipow0/keyboard/laptop-keyboard/e/k/i/mk235-mouse-logitech-original-imag3h2mzem8fyjb.jpeg?q=70",
    title: "Logitech MK235 Mouse & Keyboard Combo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Logitech",
    color: "white",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/gaming-keyboard/c/g/x/k1-mechanical-gaming-keyboard-with-blue-switches-20-rgb-original-imagxqkqyxxgbbtt.jpeg?q=70",
    title: " Wired USB Multi-device Keyboard Bestseller",   
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Logitech",
    color: "black",
    category: "keyboard",
  },

  {
    img: "https://rukminim2.flixcart.com/image/612/612/kpcy5jk0/keyboard/multi-device-keyboard/m/o/l/zeb-k-35-zebronics-original-imag3m6yggfxhtjc.jpeg?q=70",
    title: "ZEBRONICS K-35 Wired USB Multi-device Keyboard",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "ZEBRONICS",
    color: "green",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/gaming-keyboard/f/4/t/evofox-fireblade-led-backlit-amkette-original-imagrzmxfs5ua6pz.jpeg?q=70",
    title: "DELL KB 216 Wired USB Desktop Keyboard",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Dell",
    color: "red",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/i/y/h/-original-imagw4zttbhn4pdv.jpeg?q=70",
    title: "Portronics Key7 Keyboard",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Dell",
    color: "white",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/gaming-keyboard/e/l/r/hydra-10-5-0-2-4-ghz-rgb-type-c-charging-brown-switch-mechanical-original-imagtyz3zbya4gf3.jpeg?q=70",
    title: "Wireless Gaming Keyboard",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Dell",
    color: "blue",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/keyboard/desktop-keyboard/3/c/1/150-hp-original-imaghydff9ttwzex.jpeg?q=70",
    title: "HP 150 Wired USB Desktop Keyboard    ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dell",
    color: "black",
    category: "keyboard",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kw9krrk0/mouse/v/p/h/toad-13-portronics-original-imag8zbqqkgmb9d6.jpeg?q=70",
    title: "Wireless Optical Mouse",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dell",
    color: "black",
    category: "Mouse",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/korijrk0/mouse/j/p/k/b175-logitech-original-imag359v76rygsaf.jpeg?q=70",
    title: "Logitech B175 Mouse",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Logitech",
    color: "black",
    category: "Mouse",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/l3khsi80/mouse/x/r/s/toad-23-adjustable-dpi-2-4ghz-portronics-original-imagenxwgzsqub38.jpeg?q=70",
    title: "Portronics Toad 23 Mouse",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Dell",
    color: "red",
    category: "Mouse",
  },
  {
    img: "https://rukminim2.flixcart.com/image/612/612/kp1imq80/mouse/6/9/j/g102-light-sync-logitech-original-imag3d4rzzzyrfxd.jpeg?q=70",
    title: "Logitech G102 Light Mouse",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Logitech",
    color: "red",
    category: "Mouse",
  },

  {
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/mouse/t/6/s/toad-32-wireless-mouse-with-6-buttons-ergonomic-design-original-imagxz4zwqrpug3h.jpeg?q=70",
    title: "HP x1000 Wired Optical Mouse",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Dell",
    color: "black",
    category: "Mouse",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/jfbfde80/camera/n/r/n/canon-eos-eos-3000d-dslr-original-imaf3t5h9yuyc5zu.jpeg?q=70",
    title: "DSLR Camera 1 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dell",
    color: "black",
    category: "Camera",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/kbzergw0/instant-camera/r/m/h/instax-instant-camera-mini-11-fujifilm-original-imaft7fpbhhne8qr.jpeg?q=70",
    title: "FUJIFILM Instax Mini 11 Instant Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Dell",
    color: "white",
    category: "Camera",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/k3q76a80/camera/a/9/y/sony-apsc-ilce-6100l-b-in5-mirrorless-original-imafm6msv5uzrmgt.jpeg?q=70",
    title: "SONY Alpha Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Sony",
    color: "black",
    category: "Camera",
  },
  {
    img: "https://rukminim2.flixcart.com/image/312/312/xif0q/sports-action-camera/q/k/l/-original-imagnyyubc3egjzs.jpeg?q=70",
    title: "dji Action 2 Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dell",
    color: "black",
    category: "Camera",
  },
];

export default data;